add_friend/urls.py
from django.conf.urls import url
from .views import index, tambah_teman,delete


urlpatterns=[
	url(r'^$', index, name='index'),
	url(r'^tambah_teman', tambah_teman, name='tambah_teman'),
	url(r'^delete/(?P<id>\d+)/$',delete, name='delete'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

tugas1ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import dashboard.urls as dashboard
import update_status.urls as update_status
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard,namespace='dashboard')),
    url(r'^update-status/', include(update_status,namespace = 'update-status')),
    url(r'^$',RedirectView.as_view(url='/update-status/',permanent = True), name = 'index'),
    url(r'^add_friend/', include(add_friend, namespace='add_friend')),
    url(r'^halaman_profile/', include(halaman_profile, namespace='halaman_profile')),
    
    
]

add_friend/models.py
from django.db import models
from django.utils import timezone
import pytz

# Create your models here.
class new_friend(models.Model):
	name = models.CharField(max_length=27)
	heroku_link = models.CharField(max_length=100)
	created_date = models.DateTimeField(default=(timezone.now() + timezone.timedelta(hours=7)))

add_friend/views.py
from django.shortcuts import render
from .models import new_friend
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError

# Create your views here.
response = {}
response['status'] = ''
def index(request):
	#inisiasi elemen apa saja yang akan dimasukan dalam add_friend.html
	response['author'] = "Welcome to group 3 Website"
	friends = new_friend.objects.all()
	response['new_friend'] = friends
	html = 'add_friend/add_friend.html'
	return render(request,html,response) #mengirimkkan semua elemen dalam response ke alamat html


def tambah_teman(request):
	if(request.method=='POST'):
		response['name'] = request.POST['name']
		response['heroku_link'] = request.POST['heroku_link']
		url = URLValidator()
		try:
			url(response['heroku_link'])
			response['status'] = ''
			friends = new_friend(name=response['name'],heroku_link=response['heroku_link'])
			friends.save()
			response[new_friend] = friends
		except ValidationError:
			response['status'] = "Friend is not found :("
		return HttpResponseRedirect('/add_friend/')
	else:	
		return HttpResponseRedirect('/add_friend/')
		
def delete(request, id):
    friends = new_friend.objects.filter(pk=id)
    friends.delete()
    return HttpResponseRedirect('/add_friend/')

add_friend/templates/add_friend/add_friend.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

<div class="container-liquid pembungkus2">
	<header></header>
	
	<div class="container ">
		<div class="jumbotron">
      <div class="container">
        <h1>Hello, {{author}}</h1>
	        <p>Spread your connection by inviting your friends here! Click the button below</p>
        <p><a class="btn btn-primary btn-lg" role="button" href="{% url 'add_friend:index' %}#input-list">Next &raquo;</a></p>
      </div>
    </div>
	</div>

	<div class="container add-teman">
		<div class="col-md-4"></div>
		<div class="col-md-4 pembungkus1" id="input-list">
			
			<h2 class="judul1">Add Friend</h2>
			<form class="navbar-form form_add" method="POST" action="{% url 'add_friend:tambah_teman' %}">
				 	{% csrf_token %}
					<p class="font1">Your Friend's name :</p> <input type="text" placeholder="Your Friend's name" class="form-control" name="name" required>
					<span class="glyphicon glyphicon-envelope hidden-md hidden-xs hidden-sm" aria-hidden="true"></span>
					<p class="font1">Link Heroku :</p> <input type="text" placeholder="Link Heroku" class="form-control" name="heroku_link" required>
					<p><input id="submit" type="submit" class="btn btn-lg btn-block btn-info submit1" value="Submit"></p>			
			</form>
		</div>
		<div class="col-md-4">
			<h2 class="judul1" id="statusku">{{status}}</h2>
		</div>
	</div>
	<div class="container" id="my-list">
			<div class="row"><h2 align="center" id="judul-teman"><font face:"Anton|Arvo" color="#cfcfcf">Your Friend list
				<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></font></h2>
				{% if new_friend %}
				{% for data in new_friend %}
				<div class="col-md-4">
						<div class="post-it">
					<h2 class="data-nama">{{data.name}}</h2> 
					<!-- <span class="glyphicon glyphicon-user hidden-md hidden-xs hidden-sm" aria-hidden="true"></span> -->
					<h4 class="font1 data-heroku">Link Heroku :</h4>
					<a href={{data.heroku_link}} class="data-heroku text-heroku">{{data.heroku_link}}</a>
					<p class="data-heroku">{{data.created_date}}</p>
				
				<a href="{% url 'add_friend:delete' data.id %}" method="POST" class="data-delete">
                <input class="to-do-list-delete-button btn btn-lg btn-block btn-danger submit1 " method="POST" data-id="{{data.id}}" action="{% url 'add_friend:delete' data.id %}" value="Delete"></input></a>
				</div>
			</div>

				{% endfor%}
				{% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada list teman!!
            </div>
            {% endif %}

	</div>

</div>

	<footer></footer>
</div>

{% endblock %}