dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index, handle_edit_profile,show_form_edit_profile

#url for app
urlpatterns = [
    url(r'^handle_edit_profile',handle_edit_profile,name='handle_edit_profile'),
    url(r'^show_form_edit_profile',show_form_edit_profile,name='show_form_edit_profile'),
    url(r'^$', index, name='index'),
]

tugas1ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import dashboard.urls as dashboard
import update_status.urls as update_status
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard,namespace='dashboard')),
    url(r'^update-status/', include(update_status,namespace = 'update-status')),
    url(r'^$',RedirectView.as_view(url='/update-status/',permanent = True), name = 'index'),
    url(r'^add_friend/', include(add_friend, namespace='add_friend')),
    url(r'^halaman_profile/', include(halaman_profile, namespace='halaman_profile')),
    
    
]

halaman_profile/models.py
from django.db import models

# Create your models here.
class DataProfile (models.Model):
    name = models.CharField(max_length=250)
    birthday = models.CharField(max_length=20)
    gender = models.CharField(max_length=200)
    expertise = models.CharField(max_length=250)
    email = models.CharField(max_length=200)
    description = models.CharField(max_length=250)

halaman_profile/forms.py
# from django import forms
# from .views import birthdate, gender, email,desc_profile,expert,profile_name
# from .models import DataProfile

# class edit_profile_form(forms.Form):
#     profile = DataProfile.objects.get(pk=1)

#     error_messages = {
#         'required': 'Tolong isi input ini',
#     }
#     nama_attrs = {
#         'type': 'text',
#         'class': 'edit-nama-input',
#         'initial' : profile.name
#     }
#     gender_attrs = {
#         'type': 'text',
#         'class': 'edit-nama-input',
#         'initial' : profile.name
#     }
#     birthdate_attrs = {
#         'type': 'text',
#         'class': 'edit-ttl-textarea',
#         'initial' : profile.birthday
#     }
#     email_attrs = {
#         'type': 'text',
#         'class': 'edit-email-textarea',
#         'initial' : profile.email
#     }
#     expertise_attrs = {
#         'type': 'text',
#         'class': 'edit-ttl-textarea',
#         'initial' : profile.expertise
#     }
#     profile_image_attrs = {
#         'type': 'text',
#         'class': 'edit-link-textarea',
#         'placeholder':'insert link'
    
#     }
#     description_attrs = {
#         'type': 'text',
#         'cols': 50,
#         'rows': 4,
#         'class': 'todo-desc-textarea',
#         'initial' : profile.description
#     }

#     nama = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=nama_attrs))
#     birthdate = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=birthdate_attrs))
#     gender = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=gender_attrs))
#     email = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=email_attrs))
#     profile_image = forms.CharField(label='', required=True, max_length=27, widget=forms.URLInput(attrs=profile_image_attrs))
#     expertise = forms.CharField(label='', required=True, max_length=27, widget=forms.CheckBox(attrs=expertise_attrs))
#     description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=descriptions_attrs))

halaman_profile/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import DataProfile
from django.http import HttpResponseRedirect
# from .forms import edit_profile_form

# Create your views here.

profile_name = 'Gigi Hadid' #TODO implement your name here
birth_date = date(1995,4,23) #TODO implement your birthday
birthdate = birth_date.strftime('%d %B %Y')
gender = 'Female' #TODO implement your gender
email = 'gigihadid@gmail.com' #TODO implement your email
desc_profile = "victoria's secret model lalala lilili yeyeye"
#TODO implement your expertise minimal 3
# expert = ["fashion model", "actress", "wawww"]
expert = "fashion model, actress, wawww"

response = {}
def index(request):
    if (DataProfile.objects.count()==0):
        Profile = DataProfile(name= profile_name, birthday = birthdate, gender = gender,expertise = expert, email = email, description = desc_profile, id = 1 )
        Profile.save()
    profile = DataProfile.objects.first()
    response = {'Name':profile.name, 'Birthday':profile.birthday,'Gender':profile.gender,'Expertise':profile.expertise.split(","),'Email':profile.email,'Description':profile.description}
    return render(request, 'halaman_profile.html', response)
    
    #try new feature
def handle_edit_profile(request):
    # form = edit_profile_form(request.POST or None)
    # if(request.method == 'POST'and form.is_valid()):
    DataProfile.objects.all().delete()
    response['name'] = request.POST['profile_name']
    response['birthday'] = request.POST['birthdate']
    response['gender'] = request.POST['gender']
    response['expertise'] = request.POST['expert']
    response['email'] = request.POST['email']
    response['description'] = request.POST['desc_profile']
    edit = DataProfile(name= response['name'], birthday = response['birthday'], gender = response['gender'],expertise = response['expertise'], email = response['email'], description = response['description'] )
    edit.save()
    return HttpResponseRedirect('/halaman_profile/')

def show_form_edit_profile(request):
     html = "halaman_profile/edit_profile.html"
     profile = DataProfile.objects.first()
     response['profile'] = profile
     return render(request, html, response)

halaman_profile/templates/halaman_profile/edit_profile.html
{% extends "base.html" %} 
{% load staticfiles %} 
{% load static %} 

{% block content %}
<form id="form" class = "form" method="POST" action="{% url 'halaman_profile:handle_edit_profile' %}">
    <h2 style="color:White" align = "center">Edit Profile</h2>
    {% csrf_token %}
    <table align = "center"  width="600" cellspacing = "100" cellpadding="100">
        <div class="form-group">
            <td><label for="" class="control-label" style="color:White"> Nama </td></label>
            <td><input type="text" name="profile_name" class="form-control" value="{{ profile.name }}"></td>
        </div>
    
    <tr>
    <div class="form-group">
        <td><label for="" class="control-label" style="color:White"> Birthdate </td></label>
        <td><input type="text" name="birthdate" class="form-control" value="{{ profile.birthday }}"></td>
    </div>
    </tr>

    <tr>
    <div class="form-group">
        <td><label for="" class="control-label" style="color:White"> Gender </td></label>
        <td><input type="text" name="gender" class="form-control" value="{{ profile.gender }}"></td>
    </div>
    </tr>

    <tr>
    <div class="form-group">
        <td><label for="" class="control-label" style="color:White"> Expertise </td></label>
        <td><input type="text" name="expert" class="form-control" value="{{ profile.expertise }}"> </td>
    </div>
    </tr>

    <tr>
    <div class="form-group">
        <td><label for="" class="control-label" style="color:White"> Email </td></label>
        <td><input type="text" name="email" class="form-control" value="{{ profile.email }}"> </td>
    </div>
    </tr>

    <tr>
    <div class="form-group">
        <td><label for="" class="control-label" style="color:White"> Description </td></label>
        <td><input type="text" name="desc_profile" class="form-control" value="{{ profile.description }}"> </td>
    </div>
    </tr>
    <tr>
        <td><br></td>
        <td><br></td>
    </tr>
    <tr>
        <td><br></td>
        <td><br></td>
    </tr>
    <tr>
        <td><br></td>
        <td><br></td>
    </tr>
    </table>
    <table align = "center"  width="600" cellspacing = "100" cellpadding="100">
        <tr>
        <td></td>
        <td><input class="btn btn-default" align = "right" type="submit" value="Submit">
        <button class="btn btn-default" style = "right" alohref="/halaman_profile/">Cancel</button></td>
        </tr>
    </table>

</form>
{% endblock %}