dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

tugas1ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import dashboard.urls as dashboard
import update_status.urls as update_status
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard,namespace='dashboard')),
    url(r'^update-status/', include(update_status,namespace = 'update-status')),
    url(r'^$',RedirectView.as_view(url='/update-status/',permanent = True), name = 'index'),
    url(r'^add_friend/', include(add_friend, namespace='add_friend')),
    url(r'^halaman_profile/', include(halaman_profile, namespace='halaman_profile')),
    
    
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status

#url for app
urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status/$' , add_status, name='add_status')

	
	  
]

update_status/models.py
from django.db import models
from django.utils import timezone
import pytz


class Status(models.Model):
	status = models.TextField()
	created_date = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))

	

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        
    }
    status_attrs = {
        'type': 'text',
        'cols' : 149,
        'rows' : 4,
        'class' : 'status-form-input',
        'placeholder' : 'Apa yg anda pikirkan?'
    }

   
    status = forms.CharField(label='',widget=forms.Textarea(attrs=status_attrs), required=True)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
from halaman_profile.views import profile_name
from halaman_profile.models import DataProfile
##ini buat ngambil username dari halaman profile

response = {}
def index(request):
    user = DataProfile.objects.first()
    response['author'] = 'Patricia Christiana'
    response['profile_name'] = user.name    
    html = 'update_status/status.html'
    response['Status_form'] = Status_Form
    response['status'] = Status.objects.all().order_by('-id')
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status=response['status'])
        status.save()
        return HttpResponseRedirect('/update-status/')
        
    else:
        return HttpResponseRedirect('/update-status/')

update_status/templates/update_status/partials/footer.html
  <p>&copy; {{author}}</p>

update_status/templates/update_status/partials/header.html
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">
<style>
body, html {
    height: 100%;
    font-family: "Inconsolata", sans-serif;
}
.bgimg {
    background-position: center;
    background-size: cover;
    background-image: url("http://www.stellarbalcony.com/upload/all/2016/05/19/2016-05-19-1463652318-89963.jpg");
    min-height: 75%;
}
.menu {
    display: none;
}
.img-circle{
  border-radius: 50%
  width:55%;
  margin-right:2%;
  float: left;
}
.img-circle iframe{
   width:100%;
}
.w3-text-white #judul-porto {
    width:42%;
    float: left;
}
.clearfix{
    clear:both
}
</style>
<body>

<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon- bar"></span>
            <span class="icon-bar"></span>

          </button>

          <a class="navbar-brand" href="{% url 'update-status:index' %}"><img src="https://maxcdn.icons8.com/Share/icon/p1em/Very_Basic//home1600.png" alt="Form" style="width:30px;height:30px;"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
         <!--  <img src="http://imagenpng.com/wp-content/uploads/2015/09/imagenes-png.png" alt="noni" width="42" height="42" align="middle" hspace="100"> -->
            <!-- LINK MENUJU table, dan link menuju home#form -->
            
            <li><a href="{% url 'update-status:index' %}#form"> <img src="https://d30y9cdsu7xlg0.cloudfront.net/png/62816-200.png" alt="Form" style="width:30px;height:30px;"> </a></li>
          <!--   <li><a href="{% url 'update-status:result_table' %}"> <img src="https://www.shareicon.net/data/2015/08/15/85474_message_512x512.png" alt="Message" style="width:30px;height:30px;"> </a> </li> -->

              <audio controls>
              <source src="https://www.computerhope.com/jargon/m/example.mp3" />
              </audio>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


<!-- Header with image -->
<header class="bgimg w3-display-container w3-grayscale-min" id="home">
  <div class="w3-display-bottomleft w3-center w3-padding-large w3-hide-small">

   <!--  <span class="w3-tag">All About Me</span> -->
  </div>

  <div class="w3-display-middle w3-center">

    <img class = "img-circle" img src="https://i.pinimg.com/originals/46/06/18/4606187cebe4bc4fe3281cea1cf7bff3.jpg" alt="My Photo" style="width:400px;height:400px;">

    <span id="judul-porto" class="w3-text-white" style="font-size:90px"> <center>Lab 4<br></center> 
      <center>-Portofolio-</center>
    </span>
  </div>
  <div class="w3-display-bottomright w3-center w3-padding-large">
    <span class="w3-text-white"><b><i>25 September, 2017</i></b></span>  
  </div>
</header>