dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

tugas1ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import dashboard.urls as dashboard
import update_status.urls as update_status
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard,namespace='dashboard')),
    url(r'^update-status/', include(update_status,namespace = 'update-status')),
    url(r'^$',RedirectView.as_view(url='/update-status/',permanent = True), name = 'index'),
    url(r'^add_friend/', include(add_friend, namespace='add_friend')),
    url(r'^halaman_profile/', include(halaman_profile, namespace='halaman_profile')),
    
    
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status

#url for app
urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status/$' , add_status, name='add_status')

	
	  
]

update_status/models.py
from django.db import models
from django.utils import timezone
import pytz


class Status(models.Model):
	status = models.TextField()
	created_date = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=7))

	

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        
    }
    status_attrs = {
        'type': 'text',
        'cols' : 149,
        'rows' : 4,
        'class' : 'status-form-input',
        'placeholder' : 'Apa yg anda pikirkan?'
    }

   
    status = forms.CharField(label='',widget=forms.Textarea(attrs=status_attrs), required=True)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
from halaman_profile.views import profile_name
from halaman_profile.models import DataProfile
##ini buat ngambil username dari halaman profile

response = {}
def index(request):
    user = DataProfile.objects.first()
    response['author'] = 'Patricia Christiana'
    response['profile_name'] = user.name    
    html = 'update_status/status.html'
    response['Status_form'] = Status_Form
    response['status'] = Status.objects.all().order_by('-id')
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status=response['status'])
        status.save()
        return HttpResponseRedirect('/update-status/')
        
    else:
        return HttpResponseRedirect('/update-status/')

update_status/templates/update_status/status.html
{% extends "base.html" %}

{% block content %}
  <!-- Header -->
  <header class="w3-container w3-center w3-padding-48 w3-white" style="opacity:0.8;">
    <h1 class="w3-xxxlarge"><b>Group 3's Page</b></h1>
    <h6>Welcome to the blog of <span class="w3-tag">Group 3</span></h6>
  </header>

<section name="input-list" id="input-list">
    <div class="container">
<!--         <div class="row"> -->
            <div class="col-sm-500 col-sm-offset-0" id = "warnainput">
                <form id="form" method="POST" action="{% url 'update-status:add_status' %}">
                    <h2><strong>Input Status..</strong></h2>
                    {% csrf_token %}
                    {{ Status_form }}
                    <input id="submit" type="submit" class="btn btn-md btn-info" value="Submit">
                    <br>
                </form>
            </div>
        </div> 
    </div>
</section>

<section name="my-list" id="my-list" style="padding-bottom: 20px">
    {% if status %}
    <div class="container"> 
        {% for data in status %}
            <div class="kotak" style="padding-top: 15px">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <div class="media" style="padding: 40px">
                            <div class="media-left">
                                <img src="https://assets.teenvogue.com/photos/59922529fc885e5cc9aba96e/master/pass/GettyImages-546939180.jpg" class="media-object img-circle" style="width:60px"><!--foto nanti diganti dgn foto di hal profile-->
                    
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading"><strong>{{profile_name}}</strong> <small><i>Posted on {{data.created_date}}</i></small></h4><!--nama nanti diganti dgn nama di hal profile-->
                                <p>{{data.status}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-danger text-center">
            <strong>Oops!</strong> Belum ada status.
        </div>
    {% endif %}
    
</section>

{% endblock %}        